{{- if .Values.sidekiq.hpa.enabled -}}
apiVersion: {{ .Values.autoscaling.apiVersion }}
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "circuitverse.fullname" . }}-sidekiq-hpa
  labels:
    app: {{ template "circuitverse.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  scaleTargetRef:
    kind: Deployment
    apiVersion: apps/v1
    name: {{ template "circuitverse.fullname" . }}-sidekiq
  minReplicas: {{ .Values.sidekiq.hpa.minpods }}
  maxReplicas: {{ .Values.sidekiq.hpa.maxpods }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.sidekiq.hpa.cputhreshold }}
{{- end }}
