apiVersion: v1
kind: Service
metadata:
  name: circuitverse-yosys2digitaljs
spec:
  selector:
    app: circuitverse-yosys2digitaljs
  ports:
    - protocol: TCP
      port: 3040
      targetPort: 3040
  type: ClusterIP
